# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

provider "proxmox" {
  endpoint  = "https://pve.int.broodkast.eu/api2/json"
  api_token = "tfuser@pve!tfuser=a754e815-f475-4068-a24a-92ffc46f4a96"
  insecure  = true
  ssh {
    agent       = false
    username    = "terragrunt"
    private_key = "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW\nQyNTUxOQAAACCnWyl8lWMFtoplglIOUJl0bX137tnvf7y3A5N5OOEXzQAAAJisX2PBrF9j\nwQAAAAtzc2gtZWQyNTUxOQAAACCnWyl8lWMFtoplglIOUJl0bX137tnvf7y3A5N5OOEXzQ\nAAAECjRjg85dxwEqd948efF011hONnUWS5sBx0JbPHt/BkQadbKXyVYwW2imWCUg5QmXRt\nfXfu2e9/vLcDk3k44RfNAAAAFGFuc2libGVAbHhjLWF1dG9tYXRlAQ==\n-----END OPENSSH PRIVATE KEY-----"
  }
}

provider "netbox" {
  server_url = "https://netbox.int.broodkast.eu"
  api_token  = "9005421af753521ff45b24e421ddca6d99e086c9"
}

provider "adguard" {
  alias    = "primary"
  host     = "172.16.10.3" # lxc-srv-dns01
  scheme   = "http"
  username = "admin"
  password = "Jolly-Emu-Anchor2"
  insecure = true
}

provider "adguard" {
  alias    = "secondary"
  host     = "172.16.10.4" # lxc-srv-dns02
  scheme   = "http"
  username = "admin"
  password = "Jolly-Emu-Anchor2"
  insecure = true
}
