# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket = "opentofu"
    # CORRECTED: This now generates a unique key per component.
    key                         = "production/mgmt/lxc/terraform.tfstate"
    endpoint                    = "http://172.16.10.1:9000"
    region                      = "us-east-1"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    use_path_style              = true
    access_key                  = "tofu-user"
    secret_key                  = "iA.kuhqYEFLfXemF8jj7ta*X"
    insecure                    = true
  }
}
