# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    proxmox = { source = "bpg/proxmox", version = "0.79.0" }
    netbox  = { source = "e-breuninger/netbox", version = "4.1.0" }
  }
}

provider "proxmox" {
  endpoint  = "https://pve.int.broodkast.eu/api2/json"
  api_token = "tfuser@pve!tfuser=a754e815-f475-4068-a24a-92ffc46f4a96"
  insecure  = true
  ssh {
    agent       = false
    username    = "terragrunt"
    private_key = "-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACCnWyl8lWMFtoplglIOUJl0bX137tnvf7y3A5N5OOEXzQAAAJisX2PBrF9jwQAAAAtzc2gtZWQyNTUxOQAAACCnWyl8lWMFtoplglIOUJl0bX137tnvf7y3A5N5OOEXzQAAAECjRjg85dxwEqd948efF011hONnUWS5sBx0JbPHt/BkQadbKXyVYwW2imWCUg5QmXRtfXfu2e9/vLcDk3k44RfNAAAAFGFuc2libGVAbHhjLWF1dG9tYXRlAQ==-----END OPENSSH PRIVATE KEY-----"
  }
}

provider "netbox" {
  server_url = "https://netbox.int.broodkast.eu"
  api_token  = "9005421af753521ff45b24e421ddca6d99e086c9"
}
